blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
#from portfolio import views
app_name="blog"
urlpatterns = [
    path('',views.all_blogs,name='all_blogs'),
    path('white/',views.all_blogs_w,name='all_blogs_w'),
    path('<int:blog_id>/',views.details,name='details'),
    path('white/<int:blog_id>/',views.details_w,name='details_w')
]

cv/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views
#from portfolio import views
app_name="cv"
urlpatterns = [
    path('',views.cv,name='cv'),
    path('white',views.wCv,name='wCv'),
]

djangoProject1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
import portfolio.views as views
#from portfolio import views
urlpatterns = [
    path('',views.home,name='home'),
    path('white/',views.wHome,name='wHome'),
    path('admin/', admin.site.urls),
    path('cv/', include('cv.urls')),
    path('blog/', include('blog.urls'))

]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title=models.CharField(max_length=240)
    description=models.TextField()
    date= models.DateTimeField(null=False)
    #image=models.ImageField(blank=True,upload_to='cv/images/')
    #url=models.URLField(blank=True)

    def __str__(self):
        return self.title

cv/models.py
from django.db import models
class Skill(models.Model):
    name=models.CharField(max_length=120)
    perc=models.CharField(max_length=4)
    #date= models.DateTimeField(null=False)
    #image=models.ImageField(blank=True,upload_to='cv/images/')
    #url=models.URLField(blank=True)

    def __str__(self):
        return self.name
class Language(models.Model):
    name=models.CharField(max_length=120)
    perc=models.CharField(max_length=4)

    def __str__(self):
        return self.name
# Create your models here.
class Work(models.Model):
    title=models.CharField(max_length=240)
    description=models.CharField(max_length=1000)
    dateS= models.DateTimeField(null=False)
    dateE= models.DateTimeField(null=False)

    def __str__(self):
        return self.title

class Education(models.Model):
    title=models.CharField(max_length=240)
    description=models.CharField(max_length=1000)
    dateS= models.DateTimeField(null=False)
    dateE= models.DateTimeField(null=False)

    def __str__(self):
        return self.title
# Create your models here.

portfolio/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title=models.CharField(max_length=100)
    description=models.CharField(max_length=280)
    image=models.ImageField(upload_to='portfolio/images/')
    url=models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog
# Create your views here.
def all_blogs(request):
    blogs_count=Blog.objects.count()
    blogs=Blog.objects.all()
    return render(request, "blog/index.html",{'blogs':blogs,'blogs_count':blogs_count})
def all_blogs_w(request):
    blogs_count=Blog.objects.count()
    blogs=Blog.objects.all()
    return render(request, "blog//white/index.html",{'blogs':blogs,'blogs_count':blogs_count})
def details_w(request,blog_id):
    blog=get_object_or_404(Blog,pk=blog_id)
    return render(request, "blog/white/blog.html",{'blog':blog})
def details(request,blog_id):
    blog=get_object_or_404(Blog,pk=blog_id)
    return render(request, "blog/blog.html",{'blog':blog})

cv/views.py
from django.shortcuts import render
from .models import Skill,Language,Education,Work

def cv(request):
    skills=Skill.objects.all()
    languages=Language.objects.all()
    educations=Education.objects.all()
    works=Work.objects.all()
    data={"work":"Informatic","email":"jpaguiar@gmail.com", "name":"José Pedro Aguiar","phone":"927396759","local":"Viseu,PT"}
    return render(request, "cv/cv.html" ,{'works':works,'languages':languages,'educations':educations,'skills':skills,"data":data})
# Create your views here.
def wCv(request):
    skills=Skill.objects.all()
    languages=Language.objects.all()
    educations=Education.objects.all()
    works=Work.objects.all()
    data={ "work":"Informatic","email":"jpaguiar@gmail.com", "name":"José Pedro Aguiar","phone":"927396759","local":"Viseu,PT"}
    return render(request, "cv/white/cv.html" ,{'works':works,'languages':languages,'educations':educations,'skills':skills,"data":data})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects=Project.objects.all()
    return render(request, "portfolio/index.html",{'projects':projects})
def wHome(request):
    projects=Project.objects.all()
    return render(request, "portfolio/white/index.html",{'projects':projects})

blog/templates/blog/blog.html
{%  extends 'portfolio/nav.html' %}
{% block body %}
<div class="w3-text-white w3-container w3-animate-opacity">
<h2 class=" w3-center" style="color: #ff5100">{{ blog.title }}</h2>
<h6  class="w3-text-grey w3-center">{{blog.date|date:'j F Y'}}</h6>
<p>{{blog.description|safe}}</p>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
{% endblock %}

blog/templates/blog/index.html
{%  extends 'portfolio/nav.html' %}
{% block body %}
    <div class=" w3-container w3-center w3-animate-opacity ">
    <div class=" w3-text-white">
        <h2>{{blogs_count}} blog{{  blogs.count|pluralize}} {%if blogs.count != 1 %} were {%else%}was{%endif%}  written  </h2>
        </div>
        <div class="card mb-3" style="background: transparent;" >
    {% for blog in blogs %}
        <a href="{% url 'blog:details' blog.id %}" style="text-decoration: none;">
            <div>
    <div class="card-body text-white" style="background: transparent;">
        <h2 class="card-title">{{blog.title}}</h2>
        <p class="card-text">{{blog.description|striptags|truncatechars:350}}</p>
        {%if blog.data == null %}
            <h6 class="card-text"><small class="text-muted">{{blog.date}}</small></h6>
        {%endif %}


    </div></a>
        </div>
    {% endfor %}
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
{% endblock %}

blog/templates/blog/white/blog.html
{%  extends 'portfolio/white/nav.html' %}
{% block body %}
<div class="w3-text-white w3-container w3-animate-opacity">
<h2 class=" w3-center" style="color: #00aeff">{{ blog.title }}</h2>
<h6  class="w3-text-grey w3-center">{{blog.date|date:'j F Y'}}</h6>
<p>{{blog.description|safe}}</p>
</div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
{% endblock %}

blog/templates/blog/white/index.html
{%  extends 'portfolio/white/nav.html' %}
{% block body %}
    <div class=" w3-container w3-center w3-animate-opacity ">
    <div class=" w3-text-white">
        <h2>{{blogs_count}} blog{{  blogs.count|pluralize}} {%if blogs.count != 1 %} were {%else%}was{%endif%}  written  </h2>
        </div>
        <div class="card mb-3" style="background: transparent;" >
    {% for blog in blogs %}
        <a href="{% url 'blog:details_w' blog.id %}" style="text-decoration: none;">
            <div>
    <div class="card-body text-white" style="background: transparent;">
        <h2 class="card-title">{{blog.title}}</h2>
        <p class="card-text">{{blog.description|striptags|truncatechars:350}}</p>
        {%if blog.data == null %}
            <h6 class="card-text"><small class="text-muted">{{blog.date}}</small></h6>
        {%endif %}


    </div></a>
        </div>
    {% endfor %}
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
{% endblock %}

templates/portfolio/index.html
 {%  extends 'portfolio/nav.html' %}
{% block body %}

{% load static %}
    <span class="w3-hide-small w3-hide-medium m1 - m12">
    <span class="w3-hide-medium">

        <asside class="w3-text-white  w3-xxlarge w3-container w3-padding-24 w3-animate-opacity" style=" position: absolute; right:5%;top:27%;display: inline-grid;margin-right: 8%;z-index: 10;">
    <a  class="w3-text-white" href="https://www.facebook.com/josepedro.aguiar.1" target="_blank" ><i class="fa fa-facebook-official  w3-xlarge" style="margin-bottom: 60% ;margin-top: 60%"></i></a>
    <a  class="w3-text-white" href="https://www.instagram.com/josepedroaguiar/" target="_blank"><i class="fa fa-instagram  w3-xlarge" style="margin-bottom: 60% ;margin-top: 60%"></i></a>
    <a  class="w3-text-white" href="https://twitter.com/JosPedroAguiar?t=fSceoPeup8lokThrsRzRcQ&s=09" target="_blank"><i class="fa fa-twitter  w3-xlarge" style="margin-bottom: 60% ;margin-top: 60%"></i></a>
    <a  class="w3-text-white" href="https://gitlab.com/jose_aguiar" target="_blank"> <i class="fa fa-gitlab w3-xlarge" style="margin-bottom: 60% ;margin-top: 60%"></i></a>
    <a  class="w3-text-white" href="https://www.linkedin.com/in/jos%C3%A9-pedro-aguiar-219a7b225" target="_blank"><i class="fa fa-linkedin  w3-xlarge" style="margin-bottom: 60% ;margin-top: 60%"></i></a>


    </asside>
    <div class="w3-padding-large  w3-animate-left" id="main ">
    <!-- Header/Home -->

        <div class="  w3-display-container  w3-animate-opacity" style="display: inline-block;width:100%;padding-left: 20%;color: grey;">
            <div style=" display:inline-grid;padding-right: 20%">
            <h1 class="w3-jumbo" style="color: #ff5100;"><span class="w3-hide-small" style="color: white;" >I'm</span> José Aguiar.</h1>
            <p style="display: inline-block;" style="color: white;"> Software Engineer.</p>

                <form action="{% url 'cv:cv'%}">
                 <button type="submit" class="w3-btn w3-round w3-text-white w3-ripple " style="width:100px;background-color: #ff5100;"><b>My CV</b></button>
                </form>
            <br>
            </div>



            <img class="w3-image" src="{% static 'img_2.png' %}" alt="boy" style=" position: sticky;height:620px;display: inline-block;background-image:linear-gradient(120deg,#1A1C22, white);">

        </div>
   <div class="w3-content w3-justify w3-text-grey w3-padding-64" id="about" style="padding-right:20px;padding-left:20px;">
    <h2 class="w3-text-light-grey" style="padding-left:20px ;padding-right:20px">About Me</h2>
    <hr style="padding-left:20px ;padding-right:20px;width:200px;" class="w3-opacity">
    <p style="padding-right:20px;padding-left:20px ;">Some text about me. Some text about me. I am lorem ipsum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
        ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur
        adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    </p>
    </div>
        </div>

    </span>
    </span>
    <span class="w3-hide-large w3-animate-left" >
        <header class="w3-container w3-padding-32 w3-center" id="home"style="color: grey;">
        <h1 class="w3-jumbo" style="color: #ff5100;"><span class="w3-hide-small" style="color: white;" >I'm</span> José Aguiar.</h1>
        <p> Software Engineer.</p>
        <form action="{% url 'cv:cv'%}">
        <button type="submit" class="w3-btn w3-round w3-text-white w3-ripple " style="width:100px;background-color: #ff5100;"><b>My CV</b></button>

        </form>
            <br>
        <img src="{% static 'img_2.png' %}" alt="boy" class="w3-image" width="350" height="600" style="display: inline-block;">

    </header>
        <div class="w3-content w3-justify w3-text-grey w3-padding-64" id="about">
    <h2 class="w3-text-light-grey" style="padding-left:20px ;padding-right:20px">My Name</h2>
    <hr style="padding-left:20px ;padding-right:20px;width:200px;" class="w3-opacity">
    <p style="padding-right:20px;padding-left:20px ;">Some text about me. Some text about me. I am lorem ipsum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
        ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur
        adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    </p>
    </div>
    </span>
    <!-- About Section -->

    <div class="card-group "style="padding-left: 10%;padding-right: 10%;">
    {%for project in projects %}
        <div class="card" style="background: transparent;">
        <div class="card-body text-white mb-3"  style=" background-color: transparent;">
    {%if project.url %}
        <a class="w3-text-white" href="{{project.url}}" style="text-decoration:none;">
    {%else %}
        <a>
    {%endif %}
        <div>
            <img src="{{project.image.url}}" class="card-img-top" alt="..." style=" max-height:200px ;max-width:333px"><img>
    <h3 class="card-title" style=" max-height:200px ;max-width:333px">{{project.title}}</h3>
        <p class="card-text" style=" max-height:200px ;max-width:333px">{{project.description}}</p>

        </div></a>
    </div></div>

    {%endfor  %}
    </div>
    </div>

{% endblock %}

templates/portfolio/nav.html
{%  extends 'portfolio/footer.html' %}
{% block base %}
    {% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon_io-2/apple-touch-icon.png'%}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon_io-2/favicon-32x32.png'%}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon_io-2/favicon-16x16.png'%}">
    <link rel="manifest" href="/site.webmanifest">
    <title>José Aguiar</title>
</head>
<body class="body" style="background-color: #131418">

<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: transparent;">
    <div class="container-fluid">
        <div class="container-fluid">

            <a class="navbar-brand" href="{% url 'home'%}">
                <img src="{% static 'unknown.png' %}" alt="logo" width="50" height="50" class="d-inline-block align-text-top">
                <h1 class="d-inline-block align-text-top" style="padding-left:20px;">José Pedro Aguiar</h1></a>
            </a>
        </div>

        <button class="navbar-toggler ms-auto mb-1 mb-lg-0 pt-0"   style="position: absolute;left:86%;" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon d-inline-block align-text-top" style="padding-top:-100px;padding-bottom:-50px;" ></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent" >
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 " >
                <li class="nav-item ml-1 ">
                    <span class="w3-hide-small w3-hide-medium"><i class="bi bi-sun" style="color: #ff5100;"></i></span>
                </li>
                <li class="nav-item ml-1 " style="padding-left:10px;padding-right:10px;">
                    <span class="w3-hide-large"><br> <p style="color:#8f8f8f;margin-bottom: 2px">Darkmode</p></span>
                    <div class="value" id="onOffSwitch">
                        <div class="onoffswitch">
                            <label class="switch">
                                <input id="button_switch" type="checkbox" checked>
                                <div class="slider round"></div>
                            </label>
                        </div>
                    </div>
                </li>
                <li class="nav-item ml-1 "style="padding-right:20px;">
                    <span class="w3-hide-small w3-hide-medium"> <i class="fa fa-moon-o" style="color: #ff5100;"></i></span>
                </li>

                <li class="nav-item ml-1 " style="padding-left:10px;padding-right:20px;">
                    <a class="nav-link" href="{% url 'blog:all_blogs'%}">Blog</a>
                </li>
                <br>
                <li class="nav-item ml-1 " style="padding-left:10px;padding-right:20px;">
                    <form action="{% url 'cv:cv'%}">
                    <button type="submit" class="w3-btn w3-round w3-text-light-grey w3-ripple " style="width:100px;background-color: #ff5100;">CV</button>
                    </form>
                </li>

            </ul>

        </div>
    </div>
</nav>


{% block body %} {% endblock %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
<style>
    .switch {
        position: relative;
        display: inline-block;
        width: 80px;
        height: 28px;
    }

    /* Hide default HTML checkbox */
    .switch input {display:none;}

    /* The slider */
    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        -webkit-transition: .4s;
        transition: .4s;
    }

    .slider:before {
        position: absolute;
        content: "";
        height: 20px;
        width: 20px;
        left: 4px;
        bottom: 4px;
        background-color: white;
        -webkit-transition: .4s;
        transition: .4s;
    }

    input:checked + .slider {
        background-color: #ff5100;
    }

    input:focus + .slider {
        box-shadow: 0 0 1px #ff5100;
    }

    input:checked + .slider:before {
        -webkit-transform: translateX(52px);
        -ms-transform: translateX(52px);
        transform: translateX(52px);
    }

    /* Rounded sliders */
    .slider.round {
        border-radius: 28px;
    }

    .slider.round:before {
        border-radius: 50%;
    }
    img{
        z-index: 11;
    }
    i:hover{
        color: #ff5100 ;
    }
</style>
</html>
    <script>

        (function(){ //wait for load event
            var form = document.getElementById('formtoedit');
            var button = document.getElementById('button_switch');

            button.addEventListener('click',function(){
                if(this.checked){
                    window.location.href = "{% url 'home' %}";
                }else{
                    window.location.href = "{% url 'wHome' %}";
                }
            });

        })();
    </script>
{% endblock %}

templates/portfolio/switch.html
{%  extends 'portfolio/index.html' %}
<style>
</style>
{% block switch %}
<label class="switch">
    <input type="checkbox" checked>
    <span class="slider round"></span>
</label>


{% endblock %}

templates/portfolio/white/nav.html
{%  extends 'portfolio/white/footer.html' %}
{% block base %}
    {% load static %}
    <!DOCTYPE html>
    <html lang="en">
    <head>

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon_io-2/apple-touch-icon.png'%}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon_io-2/favicon-32x32.png'%}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon_io-2/favicon-16x16.png'%}">
        <link rel="manifest" href="/site.webmanifest">
        <title>José Aguiar</title>
    </head>
<body class="body" style="background-color: #ececec; filter: invert();">
<nav class="navbar navbar-expand-lg navbar-dark" style="background: transparent;">
    <div class="container-fluid">
        <div class="container-fluid">

            <a class="navbar-brand" href="{% url 'wHome'%}">
                <img src="{% static 'unknown.png' %}" alt="logo" width="50" height="50" class="d-inline-block align-text-top">
                <h1 class="d-inline-block align-text-top" style="padding-left:20px;">José Pedro Aguiar</h1></a>
            </a>
        </div>

        <button class="navbar-toggler ms-auto mb-1 mb-lg-0 pt-0"   style="position: absolute;left:86%;" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon d-inline-block align-text-top" style="padding-top:-100px;padding-bottom:-50px;" ></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 " >

                    <li class="nav-item ml-1 ">
                        <span class="w3-hide-small w3-hide-medium"> <i class="bi bi-sun" style="color: #00aeff;"></i>  </span>
                    </li>

                    <li class="nav-item ml-1 " style=" display: inline-block;padding-left:10px;padding-right:10px;">
                        <span class="w3-hide-large"><br> <p style="color:#8f8f8f;margin-bottom: 2px">Darkmode</p></span>
                        <div class="value" id="onOffSwitch">
                            <div class="onoffswitch">
                                <label class="switch">
                                    <input id="button_switch" type="checkbox">
                                    <div class="slider round"></div>
                                </label>
                            </div>
                        </div>
                    </li>

                    <li class="nav-item ml-1 "style="padding-right:20px;">
                    <span class="w3-hide-small w3-hide-medium">  <i class="fa fa-moon-o" style="color: #00aeff;"></i> </span>
                    </li>



                <li class="nav-item ml-1 " style="padding-left:10px;padding-right:20px;">
                    <a class="nav-link" href="{% url 'blog:all_blogs_w'%}">Blog</a>
                </li>
                <br>
                <li class="nav-item ml-1 " style="padding-left:10px;padding-right:20px;">
                    <form action="{% url 'cv:wCv'%}">
                    <button type="submit" class="w3-btn w3-round w3-text-black w3-ripple " style="width:100px;background-color: #00aeff;">CV</button>
                    </form>
                </li>

            </ul>

        </div>
    </div>
</nav>


{% block body %} {% endblock %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>

<style>
    .switch {
        position: relative;
        display: inline-block;
        width: 80px;
        height: 28px;
    }

    /* Hide default HTML checkbox */
    .switch input {display:none;}

    /* The slider */
    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        -webkit-transition: .4s;
        transition: .4s;
    }

    .slider:before {
        position: absolute;
        content: "";
        height: 20px;
        width: 20px;
        left: 4px;
        bottom: 4px;
        background-color: black;
        -webkit-transition: .4s;
        transition: .4s;
    }

    input:checked + .slider {
        background-color: #00aeff ;
    }

    input:focus + .slider {
        box-shadow: 0 0 1px #00aeff ;
    }

    input:checked + .slider:before {
        -webkit-transform: translateX(52px);
        -ms-transform: translateX(52px);
        transform: translateX(52px);
    }

    /* Rounded sliders */
    .slider.round {
        border-radius: 28px;
    }

    .slider.round:before {
        border-radius: 50%;
    }
    img{
        z-index: 11;
    }
    i:hover{
        color: #00aeff ;
    }

    img{
        z-index: 11;
        filter: invert();
    }
    i:hover{
        color: #00aeff ;
    }
</style>
</html>
<script>

    (function(){ //wait for load event
        var form = document.getElementById('formtoedit');
        var button = document.getElementById('button_switch');

        button.addEventListener('click',function(){
            if(this.checked){
                window.location.href = "{% url 'home' %}";
            }else{
                window.location.href = "{% url 'wHome' %}";
            }
        });

    })();
</script>

</html>

{% endblock %}